### PR TITLE
HAWQ-1190. Fix "-Wtypedef-redefinition, -Wconstant-logical-operand, -Wmemsize-comparison, -Wnull-dereference, -Wpointer-sign, -Wint-conversion" warning types.

### PR DESCRIPTION
**Pull request by xunzhang**

### CODE REVIEW

**Comment by xunzhang** [comment]
cc @paul-guo- @ictmalili @stanlyxiang

**Comment by xunzhang** [comment]
also cc @liming01

**Comment by liming01** [comment]
LGTM. +1.

**Comment by stanlyxiang** [comment]
LGTM.  +1

**Comment by xunzhang** [comment]
Merged into master.

**Pull request closed without merging**
