### PR TITLE
HAWQ-647. fix compilation flag bug in debug mode

### PR DESCRIPTION
**Pull request by xunzhang**

### CODE REVIEW

**Comment by xunzhang** [comment]
cc @changleicn @jiny2

**Comment by jiny2** [comment]
Did you tried to use O0 build to break sendWithRetry?

**Comment by xunzhang** [comment]
@jiny2 Yes, I can break sendWithRetry in my local mac, Ruilong and Yao can also successfully break sendWithRetry.

**Comment by jiny2** [comment]
@xunzhang Ok, +1.

**Comment by changleicn** [comment]
LGTM

**Comment by xunzhang** [comment]
Already merged into master, thanks.

**Pull request closed without merging**
