### PR TITLE
HAWQ-1475. Add LICENSE, NOTICE, and DISCLAIMER files for Apache HAWQ binary release

### PR DESCRIPTION
**Pull request by huor**
This commit includes:
1. The LICENSE, NOTICE, and DISCLAIMER files for Apache HAWQ c/c++ components for the binary release.
2. The build process to add the LICENSE, NOTICE, and DISCLAIMER files in Apache HAWQ binary package.

### CODE REVIEW

**Comment by huor** [comment]
@rvs, @edespino, @paul-guo- @radarwave, please review and let us know your feedback.

**Comment by rvs** [comment]
@huor I'm a bit confused -- it appears that both LICENSE and NOTICE files you added are copies of what already exists in the repo. For the binary distribution we need a much more expanded set (as per your Google doc spreadsheet) right?

**Comment by huor** [comment]
@rvs, thanks for the review and feedback.

You are right. We expand the LICENSE for source release by adding extra dependency to get that for binary release. Here is the changes:
```
rhuo-mbp:incubator-hawq rhuo$ diff dist/hawq/LICENSE LICENSE
265,270d264
<      (BSD 2 Clause) Google Mock (https://github.com/google/googletest/tree/master/googlemock)
<        depends/thirdparty/googletest/googlemock
<
<      (BSD 2 Clause) Google Test (https://github.com/google/googletest)
<        depends/thirdparty/googletest
<
347,382d340
<      contrib/extprotocol
<      contrib/formatter_fixedwidth
<      contrib/gp_cancel_query
<      contrib/hawq-hadoop
<      contrib/orafce
<      contrib/pgcrypto
<      pxf/pxf
<      src/backend/libpq
<      src/backend/port/beos/shm.c
<      src/backend/port/qnx4/shm.c
<      src/backend/utils/mb/conversion_procs/ascii_and_mic
<      src/backend/utils/mb/conversion_procs/cyrillic_and_mic
<      src/backend/utils/mb/conversion_procs/euc_cn_and_mic
<      src/backend/utils/mb/conversion_procs/euc_jis_2004_and_shift_jis_2004
<      src/backend/utils/mb/conversion_procs/euc_jp_and_sjis
<      src/backend/utils/mb/conversion_procs/euc_kr_and_mic
<      src/backend/utils/mb/conversion_procs/euc_tw_and_big5
<      src/backend/utils/mb/conversion_procs/latin2_and_win1250
<      src/backend/utils/mb/conversion_procs/latin_and_mic
<      src/backend/utils/mb/conversion_procs/utf8_and_ascii
<      src/backend/utils/mb/conversion_procs/utf8_and_big5
<      src/backend/utils/mb/conversion_procs/utf8_and_cyrillic
<      src/backend/utils/mb/conversion_procs/utf8_and_euc_cn
<      src/backend/utils/mb/conversion_procs/utf8_and_euc_jis_2004
<      src/backend/utils/mb/conversion_procs/utf8_and_euc_jp
<      src/backend/utils/mb/conversion_procs/utf8_and_euc_kr
<      src/backend/utils/mb/conversion_procs/utf8_and_euc_tw
<      src/backend/utils/mb/conversion_procs/utf8_and_gb18030
<      src/backend/utils/mb/conversion_procs/utf8_and_gbk
<      src/backend/utils/mb/conversion_procs/utf8_and_iso8859
<      src/backend/utils/mb/conversion_procs/utf8_and_iso8859_1
<      src/backend/utils/mb/conversion_procs/utf8_and_johab
<      src/backend/utils/mb/conversion_procs/utf8_and_shift_jis_2004
<      src/backend/utils/mb/conversion_procs/utf8_and_sjis
<      src/backend/utils/mb/conversion_procs/utf8_and_uhc
<      src/backend/utils/mb/conversion_procs/utf8_and_win
384,391d341
<      src/bin/gpfilesystem/hdfs/gpfshdfs.c
<      src/bin/gpoptutils
<      src/bin/gpupgrade
<      src/bin/pg_dump
<      src/include/libpq
<      src/interfaces/ecpg
<      src/interfaces/ecpg/pgtypeslib
<      src/interfaces/libpq
393,398c343,345
<      src/pl/pljava
<      src/pl/plperl
<      src/pl/plpgsql
<      src/pl/plpython
<      src/port
<      tools/bin/pythonSrc/PSI-0.3b2_gp/src
---
>      src/bin/pg_dump
>      src/backend/port/qnx4/shm.c
>      src/backend/port/beos/shm.c
```

For the NOTICE, the dependencies are either ASL v2 or category B license with no LICENSE with themselves, so there is not change according to https://cwiki.apache.org/confluence/display/GEODE/License+Guide+for+Contributors.

Please let us know your comments for further refinement. Thanks.

**Comment by huor** [comment]
@rvs, we have separate rpm packages for hawq c/c++ components, and java components (pxf, ranger). 

```hawq_rpm_packages
├── apache-hawq-2.2.0.0-el7.x86_64.rpm
├── apache-tomcat-7.0.62-el6.noarch.rpm
├── hawq-ranger-plugin-2.2.0.0-1.el7.centos.noarch.rpm
├── pxf-3.2.1.0-1.el6.noarch.rpm
├── pxf-hbase-3.2.1.0-1.el6.noarch.rpm
├── pxf-hdfs-3.2.1.0-1.el6.noarch.rpm
├── pxf-hive-3.2.1.0-1.el6.noarch.rpm
├── pxf-jdbc-3.2.1.0-1.el6.noarch.rpm
├── pxf-json-3.2.1.0-1.el6.noarch.rpm
└── pxf-service-3.2.1.0-1.el6.noarch.rpm
```

It contains LICENSE, NOTICE, and DISCLAIMER files for hawq c/c++ components in this PR, i.e., apache-hawq-2.2.0.0-el7.x86_64.rpm.

For pxf (pxf-*.rpm, apache-tomcat-7.0.62-el6.noarch.rpm) and ranger (hawq-ranger-plugin-2.2.0.0-1.el7.centos.noarch.rpm), there are incompatible license and we will do them in separate PR once your feedback for pxf and ranger part is available.

**Comment by rvs** [comment]
LGTM!

**Comment by radarwave** [comment]
LGTM +1

**Comment by huor** [comment]
Thanks @edespino for your feedback. I have bundled the license/* in hawq binary release.

**Comment by edespino** [comment]
@huor - As this has been committed, can you please close this PR now?  Thanks buddy.

**Comment by huor** [comment]
@edespino, closing the PR. Thanks for the notification.

**Pull request closed without merging**
