### PR TITLE
HAWQ-1371. Fix QE process hang in shared input scan.

### PR DESCRIPTION
**Pull request by amyrazz44**
Due to the complication of this bug. We split the fix to two parts. First of all, fix reader/writer process waits for writer/read's acks while writer/reader process may abort at the same time. Secondly, fix select endless loop.  The other fix will be committed in the other pull request.

### CODE REVIEW

**Comment by amyrazz44** [comment]
@huor @liming01 , please feel free to review, thank you.

**Comment by liming01** [comment]
+1

**Comment by huor** [comment]
+1 for the fix

**Comment by paul-guo-** [comment]
+1

**Pull request closed without merging**
