### PR TITLE
HAWQ-1125. Running pl/python related feature_test cases in parallel

### PR DESCRIPTION
**Pull request by kuien**
Prior commit: dc14ecbafc368a45cda5806ef7680ffe0825aef1

### CODE REVIEW

**Comment by paul-guo-** [comment]
+1.

By the way, I'm wondering whether the sql below works also.

-- start_ignore
CREATE LANGUAGE plpythonu;
-- end_ignore

**Comment by radarwave** [comment]
+1

**Comment by radarwave** [comment]
Merged, please close this PR. Thanks.

**Comment by kuien** [comment]
Thanks @radarwave

**Pull request closed without merging**
