### PR TITLE
HAWQ-784. Refine the document of 'hawq register'

### PR DESCRIPTION
**Pull request by Oliver-Luo**
Refine the document of 'hawq register' to give user information about data types mapping between HIVE and HAWQ.

### CODE REVIEW

**Comment by xunzhang** [comment]
@ictmalili What's the status of this pull request?

**Comment by ictmalili** [comment]
@xunzhang We haven't pull this code to master. I think we can modify the test cases part, and don't modify the document part in this pull request. What's your opinion?

**Comment by xunzhang** [comment]
@ictmalili No thoughts, just want to know the status of this pull request. Does the interface and usage included in this pull request still being discussed in mailing list?

**Comment by ictmalili** [comment]
@xunzhang No, it has already been partially finished, at least for release 2.0.1. So I think we can extract the test cases out and establish a new pull request to push the code in.

**Comment by xunzhang** [comment]
Agree.

**Comment by ictmalili** [comment]
Close this pull request, the test cases part is covered by a new pull request: https://github.com/apache/incubator-hawq/pull/782

**Pull request closed without merging**
