### PR TITLE
HAWQ-432. Memory leaks in pg_regress.

### PR DESCRIPTION
**Pull request by sansanichfb**

### CODE REVIEW

**Comment by shivzone** [comment]
Can you post the link to the updated coverity build to verify if there are no more leaks

**Comment by sansanichfb** [comment]
@shivzone I did run coverity build on local branch, not sure if this link is accessible outside.

**Comment by kavinderd** [comment]
LGTM +1

**Comment by shivzone** [comment]
good to know. +1

**Pull request merged**
