### PR TITLE
HAWQ-938. Remove ivy.xml in gpopt and read orca version from header file

### PR DESCRIPTION
**Pull request by hsyuan**
The old mechanism extracted the version numbers from the Ivy config file,
which doesn't do the right thing if you build without Ivy. Using the
version headers is simpler, anyway. Also removed `ivy.xml` and `ivy-build.xml`
under `gpopt` folder.

### CODE REVIEW

**Comment by hsyuan** [comment]
@changleicn @yaoj2 @wengyanqing 
Please take a look.

**Comment by changleicn** [comment]
@paul-guo- to review.

**Comment by paul-guo-** [comment]
+1

By the way, I just noticed the following code in gpopt.mk

UNAME = $(shell uname)
UNAME_P = $(shell uname -p)
UNAME_M = $(shell uname -m)
ARCH_OS = GPOS_$(UNAME)
ARCH_CPU = GPOS_$(UNAME_P)

ifeq (Darwin, $(UNAME))
        LDSFX = dylib
else
        LDSFX = so
endif

Please use  DLSUFFIX and PORTNAME which are defined in src/Makefile.global
(and its including makefiles),
and are generated with the configure command. This is another issue, you
could make the change in the future.

2016-07-21 9:21 GMT+08:00 Lei Chang <notifications@github.com>:

**Comment by hsyuan** [comment]
Thanks, will take care of it.

**Comment by hsyuan** [comment]
pushed to master:
https://github.com/apache/incubator-hawq/commit/78c2766578102501e67c133df942fc6355d56c8e

**Pull request closed without merging**
