### PR TITLE
Split schedule file to sanity and full tests for feature tests.

### PR DESCRIPTION
**Pull request by xunzhang**
For sanity cases in this pull request, I only split sanity cases for hawqregister to improve the CI efficiency for HAWQ developers.

### CODE REVIEW

**Comment by xunzhang** [comment]
cc @liming01

**Comment by xunzhang** [comment]
also cc @wengyanqing

**Comment by xunzhang** [comment]
also cc @radarwave

**Comment by ictmalili** [comment]
@xunzhang What's the purpose of this PR?

**Comment by xunzhang** [comment]
@ictmalili I separate the positive cases into sanity schedule for hawq register. Other cases should be separated further.

**Comment by ictmalili** [comment]
@xunzhang , Thanks. 
LGTM. +1

**Comment by paul-guo-** [comment]
+1

**Comment by xunzhang** [comment]
Merged into master, thanks.

**Pull request closed without merging**
