### PR TITLE
HAWQ-1532. recognize timezone 'CST' correctly in China

### PR DESCRIPTION
**Pull request by kuien**
On some platforms, CST (China Standard Time) is used as time string
suffix of GMT+8, especially for users in China. I tracked that change in
Postgres to this commit:

    commit e8dac6f1e09e5bc7604caa6f111d6c80a8b98295
    Author: Tom Lane <tgl@sss.pgh.pa.us>
    Date:   Wed Dec 24 16:35:23 2014 -0500

        Add CST (China Standard Time) to our lists of timezone abbreviations.

        For some reason this seems to have been missed when the lists in
        src/timezone/tznames/ were first constructed.  We can't put it in Default
        because of the conflict with US CST, but we should certainly list it among
        the alternative entries in Asia.txt.  (I checked for other oversights, but
        all the other abbreviations that are in current use according to the IANA
        files seem to be accounted for.)  Noted while responding to bug #12326.

Then, we may set timezone_abbreviations = 'Asia' to recognize CST
naturally.

### CODE REVIEW

**Comment by kuien** [comment]
On my redhat 7 server, it works like following:   

psql (8.2.15)
Type "help" for help.

postgres=# show timezone_abbreviations;
 timezone_abbreviations
------------------------
 Default
(1 row)

postgres=# select * from hawq_toolkit.hawq_log_master_concise limit 1;
            logtime            | logdatabase | logsession | logcmdcount | logseverity |
       logmessage
-------------------------------+-------------+------------+-------------+-------------+--------
---------------------------------
 2017-10-20 06:44:15.209736+08 | template1   |            |             | FATAL       | the dat
abase system is in recovery mode
(1 row)

postgres=# set timezone_abbreviations to 'Asia';
SET
postgres=# select * from hawq_toolkit.hawq_log_master_concise limit 1;
            logtime            | logdatabase | logsession | logcmdcount | logseverity |
       logmessage
-------------------------------+-------------+------------+-------------+-------------+--------
---------------------------------
 2017-10-19 16:44:15.209736+08 | template1   |            |             | FATAL       | the dat
abase system is in recovery mode
(1 row)

**Comment by radarwave** [comment]
@kuien Have you ran and passed HAWQ feature tests for this fix? Thanks.

**Comment by kuien** [comment]
@radarwave good question, I may need to add the tests as well.

**Comment by xunzhang** [comment]
```
cd $CODE_BASE
make feature-test
cd src/test/feature
./feature-test
```

**Comment by radarwave** [comment]
@kuien 
Please refer to the README of feature test to add your test:
https://github.com/apache/incubator-hawq/tree/master/src/test/feature

And you can run all the feature tests as @xunzhang mentioned above. Thanks.

**Comment by radarwave** [comment]
@kuien Do you need any help to go through the test processes?

I think at least we need this PR pass the current feature tests, then you can decide if a new test is needed for this commit.

**Comment by kuien** [comment]
@radarwave give me more time on it ... It is not easy for an Internet-engineer to prepare sufficent tests, :(

**Comment by kuien** [comment]
@xunzhang @radarwave @linwen please have a look, now this PR is not naked with tests on, LOL

Besides, I find the ```./feature-test ``` has a small issue and I record it in https://issues.apache.org/jira/browse/HAWQ-1558.

**Comment by radarwave** [comment]
Thanks @kuien .

I will test your PR in my environment since you are seeing some environment issues in HAWQ-1558.

**Comment by radarwave** [comment]
@kuien This PR passed all the tests in my environment.

+1

**Comment by radarwave** [comment]
Already merged, please close this PR. Thanks.

**Pull request closed without merging**
