### PR TITLE
HAWQ-1226. HAWQ core dump due to enable ranger while RPS is down

### PR DESCRIPTION
**Pull request by interma**
lnclude:
    1. fix core dump while RPS not running
    2. fix libcurl write_callback() problem
    3. add libcurl timeout (hard-coded 30s temporarily)
    4. fix some compile warnings
    5. fix make install error: add json.h to checkinc.py

And old PR discuss: https://github.com/apache/incubator-hawq/pull/1058

### CODE REVIEW

**Comment by interma** [comment]
@linwen @stanlyxiang @zhangh43 help to review again, thanks.

**Comment by stanlyxiang** [comment]
+1

**Comment by zhangh43** [comment]
+1

**Comment by linwen** [comment]
+1

**Pull request merged**
