### PR TITLE
HAWQ-1328. Add deny and exclude policy template for hawq service in ranger

### PR DESCRIPTION
**Pull request by zhangh43**
add option "enableDenyAndExceptionsInPolicies": "true" in ranger-servicedef-hawq.json to open deny and exclude policy template by default.

### CODE REVIEW

**Comment by zhangh43** [comment]
@denalex @linwen Please review it.

**Comment by zhangh43** [comment]
Thanks @denalex , the quote typo is fixed.
According to the Ranger document, Ranger will traverse all the deny conditions firstly to determine whether to disallow the access. And then traverse all the positive conditions.

**Comment by ictmalili** [comment]
@denalex What do you mean by "even though with deny conditions access might not be determined, the RPS will continue to interpret it as access not allowed"?  Doesn't it inherit the processing the Ranger Basic Plugin?

**Comment by denalex** [comment]
@ictmalili -- yes, it inherits, but RPS does not check isAccessDetermined() flag on the BasePluginResponse. It only checks isAccessAllowed() flag and only if it is "true" it reports to HAWQ that access is allowed, all other cases are treated as access is not allowed.

**Comment by ictmalili** [comment]
OK. Got your point, Thanks @denalex 

This commit LGTM. +1

**Pull request closed without merging**
