### PR TITLE
HAWQ-243. Remove deprecated GUCs related to planner and optimizer

### PR DESCRIPTION
**Pull request by huor**

### CODE REVIEW

**Comment by entong** [comment]
What about the optimizer_control GUC mentioned in the Jira?

**Comment by huor** [comment]
@entong, optimizer_control is neither defined nor referenced in hawq code base. The only thing needs to be done is removing optimizer_control from HAWQ 2.0 doc. This is tracked by doc team's story and they are working on it.

**Comment by yaoj2** [comment]
Looks good

**Comment by radarwave** [comment]
Looks good to me. +1

**Pull request closed without merging**
