### PR TITLE
HAWQ-1398. Fixing invalid references in log statements.

### PR DESCRIPTION
**Pull request by kdunn-pivotal**
`elog` statements attribute errors to wrong function.

### CODE REVIEW

**Comment by paul-guo-** [comment]
Maybe you could use __func__, instead of hard coding so that in case the function name is changed again......

**Comment by kdunn-pivotal** [comment]
That's a good idea. Didn't know if that capability existed in our logging infrastructure. Maybe we'll make converting all of them into a `__func__` a separate JIRA?

**Comment by paul-guo-** [comment]
elog supports formatting just like standard c function printf, etc. When I fixed a QD bug I modified some QD logs to use __func__. I think it will be a huge work to modify all, so I suggest we modify them when seeing them given this kind of bug is not functionality bug.

**Comment by paul-guo-** [comment]
+1

**Comment by huor** [comment]
+1

**Comment by kdunn-pivotal** [comment]
Looks like my Apache user `kdunn926` does not have write permissions to this repo. @edespino 

```
$ git push https://kdunn926@github.com/apache/incubator-hawq
Password for 'https://kdunn926@github.com':
remote: Permission to apache/incubator-hawq.git denied to kdunn926.
fatal: unable to access 'https://kdunn926@github.com/apache/incubator-hawq/': The requested URL returned error: 403
```

**Comment by paul-guo-** [comment]
You should check into the apache repo. github repo is just a mirror which
will keep sync-ed with the apache repo.

See
https://cwiki.apache.org/confluence/display/HAWQ/Contributing+to+HAWQ

2017-05-16 23:13 GMT+08:00 Kyle Dunn <notifications@github.com>:

**Pull request merged**
