### PR TITLE
HAWQ-1400. An improvement in SQL Util destructor function for feature test

### PR DESCRIPTION
**Pull request by jiny2**

### CODE REVIEW

**Comment by jiny2** [comment]
This is an external improvement from test tool side to make more stable CI testing.

**Comment by jiny2** [comment]
@huor @paul-guo- @stanlyxiang Please review, thanks.

**Comment by paul-guo-** [comment]
Thanks. I think at least we should add comment here at first.

**Comment by jiny2** [comment]
comment is added to explain the sleep

**Comment by huor** [comment]
+1 for the fix. The clarification looks better to have root cause

**Pull request closed without merging**
