### PR TITLE
HAWQ-1560. Changed log level to DEBUG1 for data locality messages

### PR DESCRIPTION
**Pull request by kroberts7**

### CODE REVIEW

**Comment by kuien** [comment]
LGTM

**Comment by zhangh43** [comment]
These logs will be printed only once for every call of planner.  As mentioned in [JIRA-1560](https://issues.apache.org/jira/browse/HAWQ-1560), these logs occupy 20% of the overall log. I agree to make it to DEBUG1 level.
Besides, user can still get data locality info from explain analyze.
+1

**Comment by radarwave** [comment]
@kroberts7 Thanks for your contribution. 

Now the fix is merged to master, please close this PR. Thanks.

**Comment by kroberts7** [comment]
Thank you for merging this.  Closing PR.

**Pull request closed without merging**
