### PR TITLE
HAWQ-1433. ALTER RESOURCE QUEUE DDL does not check the format of attr…

### PR DESCRIPTION
**Pull request by stanlyxiang**
…ibute MEMORY_CLUSTER_LIMIT and CORE_CLUSTER_LIMIT

### CODE REVIEW

**Comment by jiny2** [comment]
+1 LGTM

**Comment by linwen** [comment]
Does this fix mean only percentage format of MEMORY_CLUSTER_LIMIT and CORE_CLUSTER_LIMIT are supported in ALTER RESOURCE QUEUE DDL?

**Comment by stanlyxiang** [comment]
@linwen  Yes. Currently only support percentage.

**Comment by linwen** [comment]
+1

**Comment by stanlyxiang** [comment]
Merged into master. Close this PR.

**Pull request closed without merging**
