### PR TITLE
[HAWQ-19] Money type overflow fixed by back porting int64 support from Postgres commit 74a4019

### PR DESCRIPTION
**Pull request by 0x0FFF**
This commit fixes the issue [HAWQ-19](https://issues.apache.org/jira/browse/HAWQ-19) "Money type overflow" by back porting commit [74a4019](https://github.com/postgres/postgres/commit/74a40190aabd27b052ea7a63e93f7ed47743755d#diff-7ddd78dd264f8cf2a62cf572baf90b84) to HAWQ. Changes internal representation of "money" datatype, input function, cash_words function, adds function to multiply/divide cash by int8. Also changes pg_type to accommodate new internal representation

Before this commit:
```
test=# select '$30000000'::money;
      money      
-----------------
 -$12,949,672.96
(1 row)
```
After this commit:
```
test=# select '$30000000'::money;
     money      
----------------
 $30,000,000.00
(1 row)
```

### CODE REVIEW

**Comment by cwelton** [comment]
This change as on disk format implications so we must also consider the impact on upgrade.

**Comment by GodenYao** [comment]
> This change as on disk format implications so we must also consider the impact on upgrade.

Open source community generally have higher tolerance of format changes across versions I suppose?
it'd be vendors who are based on the code base may have to consider upgrade scenarios and format compatibility.

**Comment by cwelton** [comment]
Good topic for the community to discuss.  As an example the Postgres community used to take a stance of tolerance around binary version changes, but has since adopted a stronger stance around binary compatibility.  Its ultimately a question of innovation vs maintainability and strongly effects how quickly people will move from one version of the product to the next.

**Comment by 0x0FFF** [comment]
Speaking about this specific case: do we plan an upgrade path from HAWQ 1.x to 2.0? If no, then this PR can be easily merged into 2.0. If yes, we should really care about the upgrade path, and maybe the better solution here would be the following: instead of changing existing data type introduce new one, like "money8" for 8-byte money data type. This would again be a catalog change (for example, in pg_type), but still won't affect the customers using old data type "money" and layout of their existing tables

Generally speaking, I agree that this is a tough question. Postgres is not a very good example here - you can easily do pg_dump and pg_restore there as the data volumes it operates with are usually quite small. As of HAWQ, making dump and restore to accommodate storage format change can't be an option as we might have hundreds of TB there.

**Comment by changleicn** [comment]
First of all, good fix. In 2.0GA, upgrade path from hawq 1.x to 2.0 is via data reloading. Have we tested parquet format, and mapreduce inputformat? The change might have impact on these aspects?

**Comment by 0x0FFF** [comment]
Thanks for mentioning, fixed and tested Parquet compatibility

**Comment by 0x0FFF** [comment]
As of HAWQ inputformat, it never [supported "money" datatype](https://github.com/apache/incubator-hawq/blob/master/contrib/hawq-hadoop/hawq-mapreduce-common/src/main/java/com/pivotal/hawq/mapreduce/schema/HAWQPrimitiveField.java#L33):

```java
/**
 * Enumeration of all supported primitive type.
 * Note that CHAR and BPCHAR are the same, we include BPCHAR for internal usage.
 */
public static enum PrimitiveType {
	BOOL, BIT, VARBIT, BYTEA, INT2, INT4, INT8, FLOAT4, FLOAT8, NUMERIC,
	CHAR, BPCHAR, VARCHAR, TEXT, DATE, TIME, TIMETZ, TIMESTAMP, TIMESTAMPTZ, INTERVAL,
	POINT, LSEG, BOX, CIRCLE, PATH, POLYGON, MACADDR, INET, CIDR, XML
}
```
We can add it, but I think it should be a separate PR
Also it would be nice to port other "cash" functions from postgres, allowing convertation of numeric, int and float to money

**Comment by changleicn** [comment]
A PR to support "money" type and porting other "cash" functions are great.

And another suggestion is to add a installcheck-good test to cover this fix.

**Comment by 0x0FFF** [comment]
Added installcheck to cover "money" data type (both to good, serial and parallel checks)

**Comment by changleicn** [comment]
nice. LGTM.

**Comment by liming01** [comment]
Cool! 

BTW, There are 2 points here:
(1) It seems we need to add meta info for functions you added(e.g. int8_mul_cash() ) into below files:
apache-hawq/src/backend/utils/fmgrtab.c
apache-hawq/src/include/catalog/pg_operator.h
apache-hawq/src/include/catalog/pg_proc.h 

(2) I saw you changed argument type to int64 for function cash_div_int4(), but didn't change for fucntion 
cash_div_int2(). I guess you may want to fix the problem caused by (1) point above. So please revert this change. It may cause the result precision.

**Comment by liming01** [comment]
Hi Alexey,

If you need my help to move on, please let me know. Thanks.

**Comment by liming01** [comment]
I have fixed the issue I pointed out above, and merge this change into master branch. So I close this pull request.

**Comment by 0x0FFF** [comment]
Sorry, I was in a trip so didn't have time to work on this. Thank you for fixing it

**Comment by changleicn** [comment]
@0x0FFF the code is in, can you close this pull request? Thanks!

**Pull request closed without merging**
