### PR TITLE
HAWQ-711. Bugfix for libyarn/libhdfs3 building dependency. Tweak googleTest code.

### PR DESCRIPTION
**Pull request by xunzhang**

### CODE REVIEW

**Comment by xunzhang** [comment]
cc @paul-guo-

**Comment by paul-guo-** [comment]
$(MAKE) -C src feature_test clean
->
$(MAKE) -C src feature_test_clean

**Comment by xunzhang** [comment]
https://travis-ci.org/xunzhang/incubator-hawq/builds/129677006

**Comment by paul-guo-** [comment]
+1

**Comment by huor** [comment]
+1

**Pull request merged**
