### PR TITLE
[HAWQ-55] Adding dependency between optimizer_release_mdcache and gp_metadata_version

### PR DESCRIPTION
**Pull request by karthijrk**
Adding dependency between optimizer_release_mdcache and gp_metadata_version guc. Error out when both guc are set to off which is invalid state

### CODE REVIEW

**Comment by gcaragea** [comment]
Karthi, I think you need to specify the jira number in the format [HAWQ-51] no spaces etc for the pull request to be automatically linked to the jira. Otherwise, there's no notification in the jira.

**Comment by gcaragea** [comment]
+1
Looks good.

**Comment by karthijrk** [comment]
@gcaragea  Updated the title :)

**Comment by armenatzoglou** [comment]
+1

**Pull request closed without merging**
