### PR TITLE
HAWQ-1323. Fix access mode of files in adding license header added to each source file in test directory

### PR DESCRIPTION
**Pull request by amyrazz44**

### CODE REVIEW

**Comment by amyrazz44** [comment]
@huor @paul-guo-  please help review this pr, thank you

**Comment by huor** [comment]
+1

**Comment by paul-guo-** [comment]
Do not +x cpp files, else +1.

**Comment by amyrazz44** [comment]
Will fix access mode of *.cpp and *.c files in the other commit.

**Comment by huor** [comment]
@amyrazz44, please close the pr it is done.

**Pull request closed without merging**
