### PR TITLE
HAWQ-849. Remove apache orc codebase from hawq

### PR DESCRIPTION
**Pull request by xunzhang**

### CODE REVIEW

**Comment by xunzhang** [comment]
cc @liming01 @changleicn

**Comment by xunzhang** [comment]
cc @rvs , as we discuss in the mail list, we use an alternative method to support reading orc files from HDFS which does not modify the original orc repo. We could use a git submodule in the future. Also for further modification, we will send pull requests instead.

I will use mail list more often to discuss modification of organisation of hawq code. Thanks again for the good advice in https://github.com/apache/incubator-hawq/pull/701! 🍺

**Comment by liming01** [comment]
LGTM. +1.

**Comment by changleicn** [comment]
LGTM

**Comment by rvs** [comment]
@xunzhang happy to help and thanks for the patience!

**Comment by xunzhang** [comment]
Merged into master.

**Pull request closed without merging**
