### PR TITLE
HAWQ-1208. Porting gpdb interconnect fix to hawq.

### PR DESCRIPTION
**Pull request by stanlyxiang**
cc @liming01 @wengyanqing @huor

### CODE REVIEW

**Comment by huor** [comment]
Given there are multiple fix in each of commit, it is better to merge Ming's port and your fix that span in several commit into single commit. The commit message need to contain all port and fix as well. Any better option from your mind?

**Comment by liming01** [comment]
It is better to keep them separate commit, so that we can easy tracing the problem. If you think they are too many commit, you can using merge instead of rebase. 

+1.

**Comment by interma** [comment]
+1

**Comment by stanlyxiang** [comment]
Merged to master.

**Pull request closed without merging**
