### PR TITLE
HAWQ-823. Initial Amazon S3 External Table Support

### PR DESCRIPTION
**Pull request by kdunn926**
Seeing some success using GPDB S3 external protocol support:

```
# On master instance
$ PGOPTIONS='-c gp_session_role=utility' psql postgres

postgres=# CREATE OR REPLACE FUNCTION read_from_s3() RETURNS integer AS                                  '$libdir/gps3ext.so', 's3_import' LANGUAGE C STABLE;

postgres=# CREATE PROTOCOL s3 (readfunc = read_from_s3);

---

# On segment instance
$ PGOPTIONS='-c gp_session_role=utility' psql template1 -p 40000

template1=# CREATE OR REPLACE FUNCTION read_from_s3() RETURNS integer AS                                  '$libdir/gps3ext.so', 's3_import' LANGUAGE C STABLE;

template1=# CREATE PROTOCOL s3 (readfunc = read_from_s3);

---

# On master instance
$ PGOPTIONS='-c gp_session_role=utility' psql postgres

postgres=# select * from pg_extprotocol ;
 ptcname | ptcreadfn | ptcwritefn | ptcvalidatorfn | ptcowner | ptctrusted | ptcacl
---------+-----------+------------+----------------+----------+------------+--------
 pxf     |     10888 |      10887 |          10889 |       10 | t          |
 s3      |     18881 |          0 |              0 |       10 | f          |
(2 rows)
​
postgres=# CREATE READABLE EXTERNAL TABLE S3TBL (row text)
LOCATION('s3://s3.amazonaws.com/goddard.datasets/osm_exerpt_ config=/home/gpadmin/s3.conf')            FORMAT 'csv' (delimiter '>');
CREATE EXTERNAL TABLE
​
postgres=# select count(*) from S3TBL ;
  count
---------
 3995735
(1 row)
```

In order to `CREATE PROTOCOL` - I had to access both the master and segment instance (only 1 in sandbox) using utility mode to circumvent the syntax check. Not able to run the test suite as it seems to be GPDB-specific.

### CODE REVIEW

**Comment by hsyuan** [comment]
Glad to see this porting from GPDB S3

**Comment by kavinderd** [comment]
Good stuff. 

Pxf is automatically registered through `CREATE PROTOCOL` in `src/backend/catalog/cdb_external_extensions.sql`. If this is going to be a core feature of HAWQ then it makes sense to have a similar `.sql` file for this extension.

**Comment by yydzero** [comment]
Great to see s3 works with HAWQ now!

**Comment by kdunn-pivotal** [comment]
Anything else needed here? This is a critical feature both Hive and Impala already offer.

**Comment by Lwelch45** [comment]
Any idea if this is going to be moved forward?

**Comment by vVineet** [comment]
@Lwelch45 - I don't think the community members are ready to move on S3 integration just yet. There were some design discussions pending and S3 wasn't being actively worked on at the moment.

**Comment by kdunn-pivotal** [comment]
CC @tpednekar-pivotal.

**Comment by edespino** [comment]
@vVineet ... as this work is on hold, can we close this PR and revive at a later point in time?

**Comment by Jack-LiuXiong** [comment]
Hello, is there any version restriction for this practice?

**Comment by kdunn-pivotal** [comment]
Not sure which library/API version you're asking about. For the S3 API, it's likely only compatible with v4.

I'd refer to the updated _upstream_ code base for this PR here: https://github.com/greenplum-db/gpdb/tree/master/gpAux/extensions/gpcloud

The same build process I used could probably been done with this updated code.

**Pull request closed without merging**
