### PR TITLE
HAWQ-1170. Crash at cleanup_allocation_algorithm() when enable '--ena…

### PR DESCRIPTION
**Pull request by stanlyxiang**
…ble-cassert' option

### CODE REVIEW

**Comment by stanlyxiang** [comment]
@zhangh43  @xunzhang   please help to review, thanks.

**Comment by jiny2** [comment]
+1 LGTM

**Comment by jianlirong** [comment]
+1 LGTM

**Comment by zhangh43** [comment]
+1

**Comment by stanlyxiang** [comment]
Merged into master.

**Pull request closed without merging**
