### PR TITLE
HAWQ-1264. Add KEYS file for Code Signing purpose.

### PR DESCRIPTION
**Pull request by edespino**
These are the public KEYS used to validate signed artifacts.  They are use are described in the team's release process wiki section:

https://cwiki.apache.org/confluence/display/HAWQ/Release+Process%3A+step+by+step+guide

### CODE REVIEW

**Comment by paul-guo-** [comment]
Ed, could you please elaborate on the usage and purpose? Thanks.

**Comment by edespino** [comment]
@paul-guo- I added a description to the PR which describes the use of this file.

**Comment by paul-guo-** [comment]
Ok, assuming this is for release, I'm wondering whether we should put in in the release branch only since different release developers could have different keys. And if possible we should add some comments in the file (at least includes the link to the guide above).

**Comment by edespino** [comment]
I see your point, I'll close this PR and document the process to have the release manager update the PGP KEYS file in the release subversion repositories for the release.  Thanks for the great feedback.

**Pull request closed without merging**
