### PR TITLE
HAWQ-984. hawq config is too slow.

### PR DESCRIPTION
**Pull request by paul-guo-**
Further code change for the issue. Limit the worker thread number
if the queue entry number is less than the default
worker thread number (i.e. 16) since more worker thread number is
totally wasteful.

### CODE REVIEW

**Comment by xunzhang** [comment]
What's the default value?

**Comment by xunzhang** [comment]
Also, can you give the exact seconds and result of this improvement?

**Comment by paul-guo-** [comment]
6.x seconds -> 1.x seconds.

2016-08-27 16:37 GMT+08:00 Hong Wu <notifications@github.com>:

**Comment by paul-guo-** [comment]
class WorkerPool(object):
    """TODO:"""

    def __init__(self,numWorkers=16,items=None):
        self.workers=[]

**Comment by xunzhang** [comment]
+1

**Comment by radarwave** [comment]
LGTM +1

**Comment by paul-guo-** [comment]
Merged. Closing.

**Pull request closed without merging**
