### PR TITLE
HAWQ-1586. Update version from 2.2.0.0 to 2.3.0.0

### PR DESCRIPTION
**Pull request by jiny2**
postgres=# select version();
                                                                                                      version
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 PostgreSQL 8.2.15 (Greenplum Database 4.2.0 build 1) (HAWQ 2.3.0.0-incubating build dev) on x86_64-apple-darwin16.7.0, compiled by GCC Apple LLVM version 8.1.0 (clang-802.0.42) compiled on Feb  8 2018 16:34:44
(1 row)

### CODE REVIEW

**Comment by jiny2** [comment]
@radarwave @huor please help to review this version update

**Comment by huor** [comment]
LGMT +1 for the version bump

**Comment by radarwave** [comment]
Thanks @jiny2 Great to see HAWQ version upgraded to 2.3.0.0.
+1

**Comment by jiny2** [comment]
Merged into master and 2.3.0.0-incubating branches

**Pull request closed without merging**
