### PR TITLE
HAWQ-1406. Update HAWQ product version strings for 2.2.0.0-incubating release

### PR DESCRIPTION
**Pull request by huor**
Update HAWQ and HAWQ Ambari Plugin version strings for 2.2.0.0-incubating release.

### CODE REVIEW

**Comment by huor** [comment]
@edespino, @shivzone, @denalex, @radarwave, @paul-guo-, please review. Thanks.

**Comment by radarwave** [comment]
May need to add one more file:
tools/bin/gppylib/data/2.2.json (can copy from tools/bin/gppylib/data/2.1.json)

**Comment by huor** [comment]
@radarwave, right. We need that file for catalog.

**Comment by stanlyxiang** [comment]
We CAN copy. But better to GENERATE the version.json file.

**Comment by huor** [comment]
@stanlyxiang, you are right. The json need to be consistently for corresponding hawq version.

**Comment by huor** [comment]
The json file has been updated based on latest code base.

**Comment by radarwave** [comment]
LGTM  +1

**Comment by paul-guo-** [comment]
+1

**Pull request closed without merging**
