### PR TITLE
HAWQ-888. Remove some dummy files which were used to keep related "em…

### PR DESCRIPTION
**Pull request by paul-guo-**
…pty" directories.

### CODE REVIEW

**Comment by radarwave** [comment]
I think this is better than the previous hack, usually users won't create the directories by themselves.

+1

**Comment by xunzhang** [comment]
Could you add the clone info more specifically? For example, I tried your branch under my Mac and got error below, but I could not even know which repo is failed during cloning.

```
Cloning into '.'...
remote: Counting objects: 589045, done.
remote: Compressing objects: 100% (73/73), done.
error: RPC failed; curl 56 SSLRead() return error -36 251.00 KiB/s   
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
fatal: Could not parse object 'ca59dfa6f727fe3bf3a01904ec30e87f7fa5a67e'.
Now fetch from upstream and try again
From https://github.com/paul-guo-/incubator-hawq
 * branch            master     -> FETCH_HEAD
fatal: Could not parse object 'ca59dfa6f727fe3bf3a01904ec30e87f7fa5a67e'.
make[1]: *** [pgcrypto_prepare] Error 2
make: *** [all] Error 2
```

**Comment by paul-guo-** [comment]
@xunzhang, make fails because "git clone" fails, probably because of network issue or something else. This is not a makefile bug. You can try run make again. By the way, the build log includes the git command line (thus includes repo info). Just check the log before "Cloning into".

**Comment by xunzhang** [comment]
LGMT

**Pull request merged**
