### PR TITLE
HAWQ-922. Add basic verification for various pl and udf in HAWQ

### PR DESCRIPTION
**Pull request by huor**
@yaoj2, @xunzhang, @ztao1987, please review.

### CODE REVIEW

**Comment by yaoj2** [comment]
I think it is not related to upgrade. It is add UDF related test. We'd better to modify subject.

**Comment by huor** [comment]
@yaoj2, the commit message, title of the PR, and title of the JIRA has been modified to reflect that.

**Comment by yaoj2** [comment]
LGTM Thanks

**Comment by xunzhang** [comment]
+1

**Pull request closed without merging**
