### PR TITLE
HAWQ-1041. Some "top_srcdir" should be "top_builddir" in makefiles of…

### PR DESCRIPTION
**Pull request by paul-guo-**
… libhdfs3 and libyarn.

This does not affect current hawq building,but it is a bug.

### CODE REVIEW

**Comment by xunzhang** [comment]
Hi paul, could you describe the cases of this bug? Thanks.

**Comment by paul-guo-** [comment]
They (libhdfs and libyarn) should  be built under $top_builddir (build
path), although
current we have the build path identical as the source path.

2016-09-07 18:26 GMT+08:00 Hong Wu <notifications@github.com>:

**Comment by xunzhang** [comment]
LGTM

**Comment by radarwave** [comment]
LGTM +1

**Comment by paul-guo-** [comment]
Merged.

**Pull request closed without merging**
