### PR TITLE
HAWQ-82. Allocate query resource for EXPLAIN statement

### PR DESCRIPTION
**Pull request by jianlirong**

### CODE REVIEW

**Comment by zhangh43** [comment]
set query type of explain statement as QRL_ONCE to allocate resource for it.
+1

**Comment by huor** [comment]
The fix looks good to allocate resource for explain. +1

**Comment by entong** [comment]
Hi Lirong, does it mean we can support hash to random conversion in 'explain' now?

**Comment by jianlirong** [comment]
Yes, I think so. Please have a try, and let me know if anything wrong.

**Pull request merged**
