### PR TITLE
HAWQ-1113. Fix bug when files in yaml is disordered, hawq register er…

### PR DESCRIPTION
**Pull request by wcl14**
…ror in force mode.

### CODE REVIEW

**Comment by xunzhang** [comment]
Have you tested feature test cases for this modification?

**Comment by wcl14** [comment]
@xunzhang Yes, I have enabled the feature test cases for this modification.

**Comment by xunzhang** [comment]
哦

**Comment by linwen** [comment]
+1

**Comment by zhangh43** [comment]
+1

**Pull request closed without merging**
