### PR TITLE
HAWQ-1321. failNames wrongly uses memory context to build message when ANALYZE failed

### PR DESCRIPTION
**Pull request by jiny2**
set failNames use statement level context and when it potentially repallocs, switch memory context back to statement level context.

### CODE REVIEW

**Comment by jiny2** [comment]
@huor @zhangh43 @paul-guo- Please review this fix. Thank you.

**Comment by zhangh43** [comment]
+1

**Comment by paul-guo-** [comment]
+1

**Comment by huor** [comment]
@jiny2, please close the pr if it is done.

**Pull request closed without merging**
