### PR TITLE
HAWQ-948. README.md for feature test

### PR DESCRIPTION
**Pull request by xunzhang**

### CODE REVIEW

**Comment by xunzhang** [comment]
cc @liming01 @linwen

**Comment by xunzhang** [comment]
preview: https://github.com/xunzhang/incubator-hawq/blob/HAWQ-948/src/test/feature/README.md

**Comment by liming01** [comment]
+1.

**Comment by xunzhang** [comment]
also cc @wcl14

**Comment by wcl14** [comment]
+1

**Pull request merged**
