### PR TITLE
HAWQ-707. Remove gtest to dependency from libhdfs/libyarn

### PR DESCRIPTION
**Pull request by xunzhang**

### CODE REVIEW

**Comment by xunzhang** [comment]
cc @changleicn, @yaoj2, @huor, @liming01 

ps: I separate this pr into three commits with specific meaning, plz review.

**Comment by xunzhang** [comment]
Local building CI passed: https://travis-ci.org/xunzhang/incubator-hawq/builds/125908340

**Comment by liming01** [comment]
+1.

**Comment by huor** [comment]
+1

**Comment by xunzhang** [comment]
Merged & Thanks.

**Pull request closed without merging**
