### PR TITLE
HAWQ-940. Fix Kerberos ticket expired for libyarn operations

### PR DESCRIPTION
**Pull request by linwen**
Please review, thanks!

### CODE REVIEW

**Comment by linwen** [comment]
After re-think this fix, I think it's better to check ticket expiration in resource broker process loop.
so close it.

**Comment by linwen** [comment]
Another way of fix is to add the ticket check in resource broker process loop, for every time interval, login() is called. But this fix has to keep another variable to record the last updated time, which is duplicate with login().

**Comment by jiny2** [comment]
LGTM +1

**Comment by paul-guo-** [comment]
+1

**Pull request closed without merging**
