### PR TITLE
HAWQ-1221. Add register test case verify bug fix YamlFileNotExist and NonDefaultBucketnum check.

### PR DESCRIPTION
**Pull request by stanlyxiang**
cc @ictmalili @linwen @interma @xunzhang pls review. thanks.

### CODE REVIEW

**Comment by zhangh43** [comment]
+1

**Comment by linwen** [comment]
+1

**Comment by paul-guo-** [comment]
The JIRA title should be more accurate.

**Comment by stanlyxiang** [comment]
@paul-guo-  modified. Thanks.

**Pull request merged**
