### PR TITLE
HAWQ-324. Add minirepro management utility

### PR DESCRIPTION
**Pull request by hsyuan**
As a Database User, I should be able to dump the DDL and Statistics Information for a given query so I don't have to dump a large GPDB file.

GIVEN I am a Database User
WHEN I run minirepro database-name -q sql-file-name -f output-file-name
THEN I should get the DDL and statistics info for the tables and views accessed in that query

### CODE REVIEW

**Comment by xinzweb** [comment]
I understand HAWQ doesn't have behave, in this case, I want to make sure we at least have one test exercising the function of minirepro on HAWQ in the ICG. Let me create a story and follow-up on that.

**Comment by vraghavan78** [comment]
+1

**Comment by hsyuan** [comment]
@hornn can you please merge this PR?

**Comment by hornn** [comment]
Done

**Pull request merged**
