### PR TITLE
HAWQ-404. Reset default value to 160 for GUC

### PR DESCRIPTION
**Pull request by xinzweb**
optimizer_parts_to_force_sort_on_insert [#110377582]

Signed-off-by: Jacob Frank <jfrank@pivotal.io>

### CODE REVIEW

**Comment by xinzweb** [comment]
@vraghavan78 @changleicn Please take a look. Thanks.

**Comment by vraghavan78** [comment]
+1

**Comment by changleicn** [comment]
@liming01 to review and merge.

**Comment by liming01** [comment]
+1. Merged into master branch. 

@xinzweb,  could you please help me to close this PR? Thanks.

**Comment by xinzweb** [comment]
Merged: https://github.com/apache/incubator-hawq/commit/f3f91c7816acdb480fba05c374c87113a62fec9c

**Pull request closed without merging**
