### PR TITLE
HAWQ-870. Allocate target's tuple table slot in PortalHeapMemory during split partition

### PR DESCRIPTION
**Pull request by interma**
merge GPDB split-partiton optimization

Origin GPDB PR:
greenplum-db/gpdb#866

### CODE REVIEW

**Comment by interma** [comment]
@stanlyxiang @wengyanqing please help to review, thanks!

**Comment by stanlyxiang** [comment]
+1

**Comment by paul-guo-** [comment]
+1

**Comment by interma** [comment]
Thanks.

**Comment by xunzhang** [comment]
Already merged?

**Pull request closed without merging**
