### PR TITLE
HAWQ-1122. Bump GPORCA to v1.674 and GPOS to v1.145

### PR DESCRIPTION
**Pull request by xinzweb**
After the porting, HAWQ can build with `GPORCA v1.674`. However, there are few failures spotted:

**make installcheck-good**:

```
test hcatalog_lookup      ... FAILED (3.63 sec)

=======================
 1 of 15 tests failed.
=======================
```

**src/test/feature/feature-test**:

```
[==========] 167 tests from 33 test cases ran. (5760953 ms total)
[  PASSED  ] 161 tests.
[  FAILED  ] 6 tests, listed below:
[  FAILED  ] TestExternalTable.TestExternalTableAll
[  FAILED  ] TestAlterTable.TestAlterTableAOColumnNOTNULL
[  FAILED  ] TestGuc.per_db_guc_with_space
[  FAILED  ] TestType.char
[  FAILED  ] TestType.varchar
[  FAILED  ] TestQueryInsert.TestInsertWithDefaultNeg

 6 FAILED TESTS
  YOU HAVE 13 DISABLED TESTS
```

This is go beyond context of GPORCA, and we need HAWQ team to step-in, and help fixing the failed tests. @paul-guo- 

https://issues.apache.org/jira/browse/HAWQ-1122

### CODE REVIEW

**Comment by paul-guo-** [comment]
TestExternalTable.TestExternalTableAll is expected to fail.

You could check installcheck-good log, typically at least there is a file regression.diffs, but I suspect the failure is due to env setup since hcatalog_lookup seems to need a pxf service to access Hive data.

**Comment by vraghavan78** [comment]
@paul-guo- @liming01 @huor can you take it from here and merge it into the repository? Thanks.

**Comment by paul-guo-** [comment]
Moving to another PR with fixes for test cases:
https://github.com/apache/incubator-hawq/pull/983

Please close this one.

**Comment by huor** [comment]
@xinzweb, please close this pr as it has been reviewed and merged in https://github.com/apache/incubator-hawq/pull/983

**Pull request closed without merging**
