### PR TITLE
HAWQ-721. New Feature Test Skeleton.

### PR DESCRIPTION
**Pull request by xunzhang**

### CODE REVIEW

**Comment by xunzhang** [comment]
cc @wengyanqing  @huor @yaoj2

**Comment by xunzhang** [comment]
This pull request depends on https://github.com/apache/incubator-hawq/pull/629.

**Comment by wengyanqing** [comment]
+1

**Comment by xunzhang** [comment]
Usage:
1. Build Gtest/Gmock:
`cd ${HAWQ_HOME}depends/thirdparty/googletest; mkdir build; cd build;`
`cmake ..; make -j8; sudo make install;`

2. Compile Test Code:
`make feature_test;`

**Comment by xunzhang** [comment]
cc @zhangh43

**Comment by yaoj2** [comment]
+1

**Comment by xunzhang** [comment]
Merged & Thanks.

**Pull request closed without merging**
