### PR TITLE
Updating source file licensing and copyright notices

### PR DESCRIPTION
**Pull request by rvs**

### CODE REVIEW

**Comment by changleicn** [comment]
looks great!

**Comment by linwen** [comment]
Looks good. Thanks, Roman.
I am modifying pom.xml to add "PostgreSQL license" according to your suggestion.

**Comment by rvs** [comment]
Let me know when this gets merged in. I've got another PR to take care of the rest of licensing concerns.

**Comment by linwen** [comment]
Roman, would you like to merge this pull request into master? So that, I can modify pom.xml(add postgresql license and modify exclude list) based on this code change.
Thanks!

**Comment by linwen** [comment]
Roman, a new version of pom.xml has been pushed into master.
After your checkin, I will re-run mvc apache rat check and handle those new unknown files.

**Pull request closed without merging**
