### PR TITLE
HAWQ-1333. Change access mode of source files for HAWQ.

### PR DESCRIPTION
**Pull request by amyrazz44**
@radarwave  @linwen feel free to review this pr, thank you so much.

### CODE REVIEW

**Comment by radarwave** [comment]
+1

**Comment by linwen** [comment]
+1

**Comment by jinyismilodon** [comment]
Good job, please have pr delivered asap. Thanks.

**Comment by jiny2** [comment]
Good job ! please have it delivered asap. Thanks.

**Comment by xunzhang** [comment]
+1

**Pull request closed without merging**
