### PR TITLE
HAWQ-638. gpload bugfix using pip installed PyGreSQL

### PR DESCRIPTION
**Pull request by xunzhang**
See https://issues.apache.org/jira/browse/HAWQ-638 for detailed info.

### CODE REVIEW

**Comment by xunzhang** [comment]
cc @radarwave 
ps: I am not sure why Jenkins could not merge into master.

**Comment by radarwave** [comment]
+1

**Comment by yaoj2** [comment]
+1

**Comment by xunzhang** [comment]
Merged & Thanks.

**Pull request closed without merging**
