### PR TITLE
HAWQ-1214. Remove resource_parameters

### PR DESCRIPTION
**Pull request by paul-guo-**

### CODE REVIEW

**Comment by paul-guo-** [comment]
@zhangh43 @jiny2 @huor

**Comment by jinyismilodon** [comment]
+1 

One trivial comment about output int64 or unsigned int64 data, I think it is better to use INT64_FORMAT and UINT64_FORMAT instead of %lld. Though this is not actually involved in your fix.

**Comment by paul-guo-** [comment]
I agree with you. @jinyismilodon 
I've fix the code accordingly.

**Comment by zhangh43** [comment]
+1

**Pull request merged**
