### PR TITLE
HAWQ-368. Fix runawqy query cancellation issue. closes #376

### PR DESCRIPTION
**Pull request by karthijrk**
Fix the run away query termination issue - https://issues.apache.org/jira/browse/HAWQ-368

@gcaragea @armenatzoglou @foyzur Please take a look when you get chance

### CODE REVIEW

**Comment by armenatzoglou** [comment]
Is it possible to have an ICG test for this fix?

**Comment by karthijrk** [comment]
Not sure how to add ICG with simex on. If there is any suggestion please let us know.

**Comment by foyzur** [comment]
It definitely LGTM as we worked together on this one :-p So, I guess you need two more LGTM from other people.

**Comment by changleicn** [comment]
Looks the JIRA message is not the format recommended. Here is what recommended.

# <jira ticket number>. <Commit Message>
# Example: HAWQ-1002. Add awesome feature
git commit -a -m "HAWQ-1002. Add awesome feature"

**Comment by changleicn** [comment]
@liming01 to merge this pull request. It is blocking the test. It is better to merge it asap.

**Comment by liming01** [comment]
@karthijrk please close this pull request.

**Comment by karthijrk** [comment]
Thanks for the review. Closing the pull request and changes has been pushed in this commit f94b8194cb3ff12f61e8013d97a724f4f9ca9d54

**Pull request closed without merging**
