### PR TITLE
HAWQ-161. Port GPDB planner fixes to HAWQ

### PR DESCRIPTION
**Pull request by hsyuan**
Port GPDB planner fixes to HAWQ

### CODE REVIEW

**Comment by atris** [comment]
Fine for me
 +1
Please make sure that tests pass when run multiple times. Preferably tested in a buildfarm

**Comment by atris** [comment]
We were seeing transient failures for gp_optimizer earlier on hence the request

**Comment by entong** [comment]
@hsyuan, are you a committer of hawq? If not I will help you merge this.

**Comment by hsyuan** [comment]
no, I am not a committer.

Thanks~
Haisheng Yuan

**Comment by cwelton** [comment]
I see that this PR has been open for over a month.  @entong it looks like you were volunteering to handle the merge, is this still planned?  If not what can we do to get this moving forward?

**Comment by hsyuan** [comment]
Entong is not handling this PR any more. Can some committer help merge this PR back to master branch? Thanks.

**Comment by hsyuan** [comment]
@hornn Can you help me merge this PR into master? Thanks~

**Comment by hsyuan** [comment]
Merged with master:
6e2846fafe40c4259a5e81e2f5c187ff04bb8c07
ada7919105cc1dd2042e1d675a6a6690ef7b51a1
0f6beb62fa1b14a8ca1e8054c75345625cfb4464
b95ed2513983ad36651beccc721ef51bf2e70494

**Pull request closed without merging**
