### PR TITLE
HAWQ-918. Fix memtuple forming bug when null-saved size is larger tha…

### PR DESCRIPTION
**Pull request by linwen**
Please review, Thanks!

### CODE REVIEW

**Comment by xunzhang** [comment]
+1

**Comment by armenatzoglou** [comment]
LGTM.

**Comment by changleicn** [comment]
why do we still add the old installcheck tests?

**Comment by linwen** [comment]
The reason is
test cases for aggregates haven't been moved to new feature test framework yet.
So I add this test case in old installcheck.
And all the test cases for aggregates will be moved together within a new jira.

**Comment by huor** [comment]
+1

**Pull request closed without merging**
