### PR TITLE
HAWQ-320. Can't get current user name if \$USER is not set

### PR DESCRIPTION
**Pull request by radarwave**
Tested that if $USER is wrong, we still can get the correct user name.

### CODE REVIEW

**Comment by yaoj2** [comment]
+1

**Comment by huor** [comment]
The fix looks good. +1

**Comment by cwelton** [comment]
All checks passed, two +1s, what's preventing this from being merged?

**Comment by radarwave** [comment]
This already been merged, How ever not sure why the pull request not been closed automatically.

**Pull request closed without merging**
