### PR TITLE
HAWQ-597. Add Travis CI(OSX)

### PR DESCRIPTION
**Pull request by xunzhang**
Add Travis CI support under OSX, help user verify local commit before sending pull request.

More info can be found: https://travis-ci.org/xunzhang/incubator-hawq/builds/118761850

### CODE REVIEW

**Comment by xunzhang** [comment]
@cjcjameson plz review

**Comment by cjcjameson** [comment]
@xunzhang thank you for your pull request and contribution to HAWQ! I would also want to loop in another contributor, Michael Schubert.

**Comment by schubert** [comment]
I saw this warning in the build:

`This log is too long to be displayed. Please reduce the verbosity of your build or download the raw log.`

Due to what looks like Travis's limitation of 10,000 lines displayed for the build log, I would recommend you pipe non-essential information to a file and only print out in an error condition so you minimize the log noise and usually only see essential build output without having to look at the raw log.

you can do this for example with brew update: 

```bash
brew update 2>&1 > /tmp/brew-update.txt || (cat /tmp/brew-update.txt && false)
```

Redirect stderr to stdout and if you get a non-zero exit, print out the logfile of what happened and stop the build. 

I think you would want to do this for everything in the `before_install` and in the `install` with the exception of libhdfs3 due to it being a tightly coupled and relevant dependency. Maybe move libhdfs3 down into the before_script to make that separation clear?

Hopefully with that all of the critical build steps relevant to HAWQ itself will be displayed the vast majority of the time to make it more developer friendly.

**Comment by xunzhang** [comment]
@schubert Thank you for the advice, I modified the `brew update` and move `libhdfs3` into `before_script` into another commit. Since all `install` info take only less than 200 lines and travis will fold these info automatically, I don't modify `install` for the code simplicity. Check out https://travis-ci.org/xunzhang/incubator-hawq/builds/119114627.

**Comment by schubert-apt** [comment]
Yup that looks like a better solution and you've got another 1300 log lines to spare. LGTM.

**Comment by schubert** [comment]
Yup that looks like a better solution and you've got another 1300 log lines to spare. LGTM.

**Comment by cjcjameson** [comment]
+1

**Comment by xunzhang** [comment]
Already merged into master by @radarwave, so I will close.

**Comment by xunzhang** [comment]
Already merged into master by @radarwave, so I will close.

**Pull request closed without merging**
