### PR TITLE
HAWQ-1327. Move ID from struct SegStatData to struct SegInfoData so t…

### PR DESCRIPTION
**Pull request by paul-guo-**
…hat ID could be used in QD.

This also fixes some warnings and some minor bugs which are found during warning fixing.

### CODE REVIEW

**Comment by paul-guo-** [comment]
@jiny2

**Comment by paul-guo-** [comment]
@huor

**Comment by jiny2** [comment]
+1 LGTM Thank you for improving RM component

**Comment by huor** [comment]
+1

**Comment by paul-guo-** [comment]
Merged.

**Pull request closed without merging**
