### PR TITLE
HAWQ-1183. Writable external table with Hash distribution shows slow …

### PR DESCRIPTION
**Pull request by paul-guo-**
…performance

This fixes some warnings also in the affected source file.

### CODE REVIEW

**Comment by paul-guo-** [comment]
I thought adding a case, but it seems that it is hard to add one in the current framework.

**Comment by xunzhang** [comment]
ok, maybe we could test it manually for this.

**Comment by paul-guo-** [comment]
@zhangh43

**Comment by paul-guo-** [comment]
@huor

**Comment by zhangh43** [comment]
+1 for external table bucket number change.

**Comment by huor** [comment]
+1

**Comment by paul-guo-** [comment]
Merged.

**Pull request closed without merging**
