### PR TITLE
HAWQ-1434 :  FIX: pxf jdbc plugin - case problems with mysql on linux

### PR DESCRIPTION
**Pull request by michaelandrepearce**
Remove forced upper casing on table name.

### CODE REVIEW

**Comment by paul-guo-** [comment]
@michaelandrepearce  If the code change has been in main, please close this PR. Thanks.
By the way, it would be better to have the PR title with more details (i.e. not just a JIRA ID).

**Comment by michaelandrepearce** [comment]
I haven't seen a merge

**Comment by paul-guo-** [comment]
@shivzone Please help to take a look at the patch.

**Comment by sansanichfb** [comment]
Merged to master.

**Pull request closed without merging**
