### PR TITLE
HAWQ-1448. Fixed postmaster process hung at recv () on segment

### PR DESCRIPTION
**Pull request by liming01**
Hi all,

I don't know is there any side effect of this fix, but I think from theory it should be okay, so prefer to to checkin and monitor for a period of time. Please help me to review it. Thanks.

### CODE REVIEW

**Comment by paul-guo-** [comment]
Normally stopped master should not lead to recv() hang on segments since recv() will return 0 if the tcp connection (libpq) is closed.

**Comment by edespino** [comment]
@liming01 - What is the status of this PR?  It's been idle for over a month.

**Comment by liming01** [comment]
@edespino,  if we can find all hung root cause when hawq stop and fix them, then we don't need this PR. 

However from a long time investigate, these problems still cannot been fixed. So I suggest to apply this PR. This PR can fix all hung problems when hawq stop, (if still hung in some cases, we should check not disable interrupt processing during the hung function called).

Thanks.

**Comment by radarwave** [comment]
When master is down,  it's no matter to stop segment in 'smart' or 'fast' mode. And I see this fix only affect 'hawq stop cluster', which means master is already down before stoping segments. So I think this fix is good enough to me.

+1

**Comment by wengyanqing** [comment]
Agree with Radar's comment. LGTM.

**Pull request closed without merging**
